### PR TITLE
Export CIRCLE_JDK_VERSION in circle config

### PR DESCRIPTION
**Pull request by brennan**
- Export CIRCLE_JDK_VERSION in Circle config so we can deploy snapshots

### CODE REVIEW

**Comment by f2prateek** [comment]
Don't think this is enough on it's own - you need to to add credentials for segment-bot as well.

**Comment by brennan** [comment]
@f2prateek Do you have an example of where to add these credentials? I thought the oracle jdk was the only missing piece to test snapshot deployment via circle. Thanks!

**Comment by f2prateek** [comment]
https://circleci.com/gh/segment-integrations/analytics-android-integration-mixpanel/edit#env-vars

**Comment by brennan** [comment]
@f2prateek I get a 404 here.

**Comment by f2prateek** [comment]
make sure you login?

**Pull request closed without merging**
